### ISSUE TITLE
Request for better name or refactor

### ISSUE THREAD

**Issue by midischwarz12** [Emmanuel-Aaron/rom-623#2]
https://github.com/Emmanuel-Aaron/rom-623/blob/integration/src/system/algorithm.c

Algorithm is too generic. So this object is meaningless.

**Comment by Aaron-Roar** [comment]
This will be renamed to scheduling_algorithms.c

Refactoring is definitely something that must take place as many of the functions defined in algorithm.c are not specific to scheduling algorithms.
