### ISSUE TITLE
Possibly related

### ISSUE THREAD

**Issue by midischwarz12** [Emmanuel-Aaron/rom-623#3]
https://github.com/Emmanuel-Aaron/rom-623/tree/integration/src/sensors/altitude

https://github.com/Emmanuel-Aaron/rom-623/blob/integration/src/tasks/altitude.c

**Comment by Aaron-Roar** [comment]
These are actually not related as the altitude in the tasks/ directory is the implementation of using the barometer/altimeter API in the sensors/altitude/ directory.

The tasks are generic instructions which preform an operation of the aircraft. These should be thought as independent from specific sensors, motors, or that of any hardware/electrical component at an abstract view.
