### ISSUE TITLE
Makefile and possible separate app

### ISSUE THREAD

**Issue by midischwarz12** [Emmanuel-Aaron/rom-623#5]
https://github.com/Emmanuel-Aaron/rom-623/tree/integration/src/sensors/gyro

Should use malefile instead of build.sh. Also, is this also a ssperate application? If so, amend to #4

**Comment by Aaron-Roar** [comment]
This is not a separate application as the API is not general purpose and is specific to this application. In future a more general API will written which will make the API a standalone application.
