### ISSUE TITLE
Too early for integrating feature

### ISSUE THREAD

**Issue by midischwarz12** [Emmanuel-Aaron/rom-623#6]
https://github.com/Emmanuel-Aaron/rom-623/blob/integration/src/arduino/interupt/interupt.ino

Looks like the loop isn't defined. And there's a bunch of test functions without proper names. This should be in a separate branch before merging.

**Comment by Aaron-Roar** [comment]
The arduino interrupt should have never been merged until it was fully operational in an isolated test environment. This is a mistake we made during last minuet development.

The feature will be removed and integrated back when it is fully operational.
